App skeleton, scss, useState
MartSe1991/ToDoApp pull request #1
Opened 2023-08-23 12:36 UTC by MartSe1991

2023-08-23 16:35 UTC, salvoguastella commented
A livello visivo la schermata è abbastanza differente dai design. Prova ad impostarla in maniera che non ci siano margini inutilizzati, spazi superflui e che la parte sx e destra del corpo della pagina prendano tutto lo spazio disponibile, ma senza provocare lo scrolling della pagina.

2023-08-23 16:44 UTC, salvoguastella requested changes

2023-08-23 16:44 UTC, salvoguastella commented on src/components/MainMenu/AddNewToDoItem.jsx
Questo component ed il relativo style module potrebbero andare in una cartella separata.
Inoltre, attenta al nome: al momento stai utilizzando questo component per aggiungere liste all'elenco, non item ad una lista. Potresti riutilizzarlo per entrambi i casi in realtà con davvero pochissime modifiche.

Personalmente lo rinominerei `AddNewItemForm`

2023-08-23 16:44 UTC, salvoguastella commented on src/components/UI/Button.module.scss
> +  font: $medium;
questo dovrebbe essere `font-size`

2023-08-23 16:44 UTC, salvoguastella commented on src/components/UI/Button.module.scss
Essendo questo un file `scss`, potresti utilizzare la sintassi annidata per avere una regola principale `.button` e al suo interno `&:hover`, `&:active` e `&:focus`

2023-08-23 16:44 UTC, salvoguastella commented on src/components/UI/Button.module.scss
> +  border-color: $secondary;
al momento questa regola visivamente non fa nulla, essendo questi colori gli stessi di quelli di base

2023-08-24 07:42 UTC, MartSe1991 commented on src/components/MainMenu/AddNewToDoItem.jsx
Non ho capito!!

2023-08-24 07:45 UTC, MartSe1991 commented on src/components/UI/Button.module.scss
Fatto!

2023-08-24 07:48 UTC, MartSe1991 commented on src/components/UI/Button.module.scss
> +  border-color: $secondary;
Fatto!!

2023-08-24 08:42 UTC, MartSe1991 commented on src/components/MainMenu/AddNewToDoItem.jsx
Fatto!!

2023-08-24 16:20 UTC, salvoguastella requested changes

2023-08-24 16:20 UTC, salvoguastella commented on src/components/UI/Button.module.scss
> +  font: $medium;
Non è risolto!

2023-08-24 16:20 UTC, salvoguastella commented on src/components/UI/Button.module.scss
> +  // }
Servono queste righe?

2023-08-24 16:20 UTC, salvoguastella commented on src/components/UI/Button.jsx
> +      <div>+</div>
Dovresti aggiungere un po di styling a questo `+` in modo da renderlo più simile al design fornito

2023-08-24 16:20 UTC, salvoguastella commented on src/components/MainMenu/Menu.jsx
> +      <AddNewElem onNewItemHandler={onAddItem} />
Questo è qua solo per fare spacchiamento pennuto no? Lo sposterai nella modal no?

2023-08-24 16:47 UTC, MartSe1991 commented on src/components/UI/Button.module.scss
> +  font: $medium;
Risolto ora!!!

2023-08-24 16:47 UTC, MartSe1991 commented on src/components/UI/Button.module.scss
> +  // }
Si per ora!!!

2023-08-24 16:49 UTC, MartSe1991 commented on src/components/MainMenu/Menu.jsx
> +      <AddNewElem onNewItemHandler={onAddItem} />
Perche dovrei?

2023-08-24 19:12 UTC, salvoguastella approved these changes

2023-08-25 10:23 UTC, merged