pencil icon/ moved folders/ edit props& modal comp
MartSe1991/ToDoApp pull request #10
Opened 2023-11-02 12:00 UTC by MartSe1991

Mi aiuti a risolvere problema dell'icona che non si vede?

2023-11-02 16:54 UTC, salvoguastella requested changes

2023-11-02 16:54 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.jsx
> +import AddNewElemAnchor from "../AddNewElemAnchor/AddNewElemAnchor";
Utilizza @components quando puoi, è più facile da leggere

2023-11-02 16:54 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.jsx
> +import EditElemModal from "../EditElemModal/EditElemModal";
Anche qui @components

2023-11-02 16:54 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.jsx
> +import EditElemModal from "../EditElemModal/EditElemModal";
Chiama questo component `EditElemAnchor` in modo da essere coerente con l'altro component

2023-11-02 16:54 UTC, salvoguastella commented on src/components/AddNewElemAnchor/AddNewElemAnchor.jsx
> +import Modal from "../UI/Modal/Modal";
Usa @components

2023-11-02 16:54 UTC, salvoguastella commented on src/components/EditElemModal/EditElemModal.jsx
> +const EditElemModal = ({ size, className }) => {
Chiama questo component e la cartella che lo contiene `EditElemAnchor`

2023-11-02 16:54 UTC, salvoguastella commented on src/components/EditElemModal/EditElemModal.module.scss
Questo file può quindi chiamarsi `EditElemAnchor.modal.scss`

2023-11-02 16:54 UTC, salvoguastella commented on src/components/UI/Icons/EditPencil.jsx
> +      stroke={Colors}
Mi sa che ti sei dimenticata di scegliere il colore da usare. Qui stai assegnando tutto l'object alla proprietà `stroke`. Per questo non vedi niente

2023-11-02 16:54 UTC, salvoguastella commented on src/components/UI/Modal/Modal.jsx
>      // setEnteredListItem("");
puoi eliminare questo commento

2023-11-04 02:12 UTC, salvoguastella requested changes

2023-11-04 02:12 UTC, salvoguastella commented on src/components/MainMenu/Menu.jsx
> +            {<EditElemAnchor size="18" className={classes.edit_icon} />}
Occhio che quando fai hover la riga cambia di altezza e il layout sotto salta! Prova a dare un'altezza fissa alla riga o a regolare meglio lo spacing tra gli elementi della lista. Magari puoi risolvere facilmente usando la regola `gap` sul container

2023-11-04 20:27 UTC, MartSe1991 commented on src/components/MainMenu/Menu.jsx
> +            {<EditElemAnchor size="18" className={classes.edit_icon} />}
fatto!

2023-11-09 15:56 UTC, salvoguastella requested changes

2023-11-09 15:56 UTC, salvoguastella commented on src/App.jsx
> +  const editListHandler = (uItem, itemIndex) => {
aggiungi un commento per spiegare cosa fa questa funzione

2023-11-09 15:56 UTC, salvoguastella commented on TODO.md
> +
Puoi rimuovere questo blocco e scrivere:

- add typescript
- add contexts
- refactor some code in custom hooks
- delete confirmation modal

Sono le cose che ti mostrero!

2023-11-09 16:34 UTC, salvoguastella approved these changes

2023-11-09 16:35 UTC, merged