Modal styling changes
MartSe1991/ToDoApp pull request #2
Opened 2023-08-25 14:49 UTC by MartSe1991

2023-08-25 20:29 UTC, salvoguastella requested changes

2023-08-25 20:29 UTC, salvoguastella commented on src/components/AddNewElemModal/Modal.module.scss
> +  // gap: 150px;
questo puoi rimuoverlo

2023-08-25 20:29 UTC, salvoguastella commented on src/components/UI/Button/AddButton.jsx
> +      <div>+</div>
Questo `+` non é ancora stilizzato!

2023-08-26 06:31 UTC, MartSe1991 commented on src/components/AddNewElemModal/Modal.module.scss
> +  // gap: 150px;
Done!!

2023-08-26 06:49 UTC, MartSe1991 commented on src/components/UI/Button/AddButton.jsx
> +      <div>+</div>
Fatto!!! Dimmi cosa ne pensi!!

2023-08-26 09:25 UTC, salvoguastella approved these changes

2023-08-26 12:22 UTC, merged