list box
MartSe1991/ToDoApp pull request #4
Opened 2023-08-30 16:41 UTC by MartSe1991

2023-08-30 17:02 UTC, salvoguastella requested changes

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.module.scss
> +  // text-decoration: line-through;
questo puoi cancellarlo

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/TickBox.module.scss
> +// }
lo puoi cancellare

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/TickBox.jsx
> +    />
questa implementazione va bene, ma tieni a mente che esiste già un elemento HTML per mostrare una checkbox:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/TickBox.jsx
> +const TickBox = ({ onClick, tickBox }) => {
la prop `tickBox` la chiamerei `selected`

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.jsx
> +  const [tickBox, setTickBox] = useState(false);
questo state non serve. Ogni elemento viene selezionato individualmente.

2023-08-30 17:02 UTC, salvoguastella commented on src/components/ActiveList/ActiveList.jsx
> +            <TickBox onClick={tickBoxHandler} tickBox={tickBox} />
Visto che non dobbiamo usare uno state unico, dobbiamo sostituire l'onClick e tickBox (o meglio `selected)` con qualcos'altro. 
Ricorda: ogni elemento mappato è un object con due prop: `name` e ...?

2023-08-30 17:09 UTC, MartSe1991 commented on src/components/ActiveList/ActiveList.module.scss
> +  // text-decoration: line-through;
Fatto!

2023-08-30 17:09 UTC, MartSe1991 commented on src/components/ActiveList/TickBox.module.scss
> +// }
fatto

2023-09-07 18:55 UTC, salvoguastella approved these changes

2023-09-07 18:55 UTC, merged